"""add student_class table

Revision ID: 0ea2e2af4bcc
Revises: 6be19d799ebc
Create Date: 2026-04-16 02:56:56.761205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ea2e2af4bcc'
down_revision = '6be19d799ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_class',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('student_id', sa.String(length=50), nullable=False),
                    sa.Column('teaching_class_id', sa.String(length=50), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('joined_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
                    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_class.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('student_id', 'teaching_class_id', name='uq_student_class')
                    )
    op.create_index(op.f('ix_student_class_student_id'), 'student_class', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_class_teaching_class_id'), 'student_class', ['teaching_class_id'], unique=False)
    op.alter_column('ai_chat_conversation', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_chat_conversation', 'updated_at',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_ai_chat_conversation_teacher_scope_updated'), table_name='ai_chat_conversation')
    op.alter_column('ai_chat_memory_fact', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_chat_message', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_ai_chat_message_conversation_created_at'), table_name='ai_chat_message')
    op.alter_column('management_system_record', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('management_system_record', 'updated_at',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('management_system_record', 'updated_at',
                    existing_type=mysql.DATETIME(),
                    nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('management_system_record', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_chat_message_conversation_created_at'),
                    'ai_chat_message', ['conversation_id', 'created_at'], unique=False)
    op.alter_column('ai_chat_message', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_chat_memory_fact', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_chat_conversation_teacher_scope_updated'), 'ai_chat_conversation',
                    ['teacher_user_id', 'management_system_id', 'updated_at'], unique=False)
    op.alter_column('ai_chat_conversation', 'updated_at',
                    existing_type=mysql.DATETIME(),
                    nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_chat_conversation', 'created_at',
                    existing_type=mysql.DATETIME(),
                    nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_student_class_teaching_class_id'), table_name='student_class')
    op.drop_index(op.f('ix_student_class_student_id'), table_name='student_class')
    op.drop_table('student_class')
    # ### end Alembic commands ###
