"""init

Revision ID: 458a6439192a
Revises:
Create Date: 2026-04-05 22:05:31.259802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '458a6439192a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('instruction_steps', sa.JSON(), nullable=True))
    op.add_column('assignment', sa.Column('attachments', sa.JSON(), nullable=True))
    op.alter_column('assignment', 'course_id',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    op.drop_index(op.f('uq_assignment_attachment_upload_file_key'), table_name='assignment_attachment_upload')
    op.drop_index(op.f('ix_assignment_attachment_upload_file_key'), table_name='assignment_attachment_upload')
    op.create_index(op.f('ix_assignment_attachment_upload_file_key'),
                    'assignment_attachment_upload', ['file_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_attachment_upload_file_key'), table_name='assignment_attachment_upload')
    op.create_index(op.f('ix_assignment_attachment_upload_file_key'),
                    'assignment_attachment_upload', ['file_key'], unique=False)
    op.create_index(op.f('uq_assignment_attachment_upload_file_key'),
                    'assignment_attachment_upload', ['file_key'], unique=True)
    op.alter_column('assignment', 'course_id',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    op.drop_column('assignment', 'attachments')
    op.drop_column('assignment', 'instruction_steps')
    # ### end Alembic commands ###
