"""create attachment table

Revision ID: 598db41b7983
Revises: 0ea2e2af4bcc
Create Date: 2026-04-21 19:15:16.602653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598db41b7983'
down_revision = '0ea2e2af4bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('management_system_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['management_system_id'], ['management_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_management_system_deleted', 'attachment', ['management_system_id', 'deleted_at'], unique=False)
    op.create_index('idx_owner_type_id', 'attachment', ['owner_type', 'owner_id'], unique=False)
    op.create_index(op.f('ix_attachment_management_system_id'), 'attachment', ['management_system_id'], unique=False)
    op.create_index(op.f('ix_attachment_owner_id'), 'attachment', ['owner_id'], unique=False)
    op.create_index(op.f('ix_attachment_owner_type'), 'attachment', ['owner_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachment_owner_type'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_owner_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_management_system_id'), table_name='attachment')
    op.drop_index('idx_owner_type_id', table_name='attachment')
    op.drop_index('idx_management_system_deleted', table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
