"""drop image_paths column from submission

Revision ID: 78fe51bc0983
Revises: 598db41b7983
Create Date: 2026-04-21 19:48:31.853067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fe51bc0983'
down_revision = '598db41b7983'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
